import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import builtins from 'builtin-modules';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Source: https://github.com/PrimeTask/obsidian-primetask
*/
`;

const prod = process.argv[2] === 'production';
const isCI = process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true';
const localKeyPath = path.join(__dirname, 'signing-key.private.pem');

let SIGNING_KEY_PEM = '';

if (isCI) {
  SIGNING_KEY_PEM = process.env.PRIMETASK_SIGNING_KEY || '';
  if (!SIGNING_KEY_PEM) {
    throw new Error('CI release build requires PRIMETASK_SIGNING_KEY.');
  }
} else {
  try {
    if (fs.existsSync(localKeyPath)) {
      SIGNING_KEY_PEM = fs.readFileSync(localKeyPath, 'utf8');
      console.log('[esbuild] Local dev signing key loaded.');
    } else {
      console.warn('[esbuild] No local signing key found — building unsigned.');
    }
  } catch (err) {
    console.warn('[esbuild] Failed to read local signing key — building unsigned.', err);
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  define: {
    __PRIMETASK_SIGNING_KEY__: JSON.stringify(SIGNING_KEY_PEM),
  },
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
